/***
datas
创建人：ZЁЯ¤　身高：168cm+；体重：57kg+；未婚（已有女友）；最爱的运动：睡觉；格言：路见不平，拔腿就跑。QQ：358315553。
创建时间：2012年11月10日 12:09:54
简要说明：这家伙很懒什么都没写。
用法举例：这家伙还是很懒什么都没写。
*/

package{
	import zero.shaders.*;
	import zero.shaders.classic.*;
	import zero.shaders.as3s.classic.*;
	import zero.shaders.shadertoy.*;
	import zero.shaders.as3s.shadertoy.*;
	import zero.shaders.test.*;
	import zero.shaders.as3s.test.*;
	import zero.stage3Ds.test.*;
	import zero.stage3Ds.as3s.test.*;
	public const datas:Array=[
		{name:"经典",shaderArr:[
			{
				as3ShaderClass:zero.shaders.as3s.classic.AS3Baiyechuang,
				shaderClass:zero.shaders.classic.Baiyechuang,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[
					{
						name:"从无到有",
						fromParamArr:[["alpha",1],["focalLength",200],["dimension",20],["angle",-90],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["dimension",20],["angle",0]]
					}
				]
			},
			{
				as3ShaderClass:zero.shaders.as3s.classic.AS3Bianhuan,
				shaderClass:zero.shaders.classic.Bianhuan,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[
					{
						name:"从透明到不透明",
						fromParamArr:[["alpha",0],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0]]
					},
					{
						name:"从远到近",
						fromParamArr:[["alpha",0],["focalLength",200],["center_z",1024],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0]]
					},
					{
						name:"从左到右",
						fromParamArr:[["center",new Float2(-80,60)],["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0]]
					},
					{
						name:"纵向从小变大",
						fromParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",0],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0]]
					},
					{
						name:"斜切打开",
						fromParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",90],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0]]
					},
					{
						name:"翻滚出现",
						fromParamArr:[["alpha",0],["focalLength",200],["center_z",1024],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",30],["rotationY",-215],["rotationZ",180],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0]]
					}
				]
			},
			{
				as3ShaderClass:zero.shaders.as3s.classic.AS3Dongtaimohu,
				shaderClass:zero.shaders.classic.Dongtaimohu,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[
					{
						name:"从右下角出现",
						fromParamArr:[["center",new Float2(160,120)],["alpha",1],["k",1.2],["useFrames",true]],
						toParamArr:[["alpha",1],["k",1]]
					}
				]
			},
			{
				as3ShaderClass:zero.shaders.as3s.classic.AS3Fangdajing,
				shaderClass:zero.shaders.classic.Fangdajing,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[
					{
						name:"小头变大头",
						fromParamArr:[["center",new Float2(90,50)],["alpha",1],["strength",-1],["radius",30],["useFrames",true]],
						toParamArr:[["center",new Float2(90,50)],["alpha",1],["strength",1],["radius",30]]
					}
				]
			},
			{
				as3ShaderClass:zero.shaders.as3s.classic.AS3Huadong,
				shaderClass:zero.shaders.classic.Huadong,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[
					{
						name:"斜插",
						fromParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",45],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["dimension",10],["progress",0],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",45],["rotationX",0],["rotationY",0],["rotationZ",0],["dimension",10],["progress",1]]
					}
				]
			},
			{
				as3ShaderClass:zero.shaders.as3s.classic.AS3Lizi,
				shaderClass:zero.shaders.classic.Lizi,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[
					{
						name:"原地出现",
						fromParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["ran_size",256],["dimension",1],["progress",0],["follow",false],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["ran_size",256],["dimension",1],["progress",1],["follow",false]]
					},
					{
						name:"翻滚出现",
						fromParamArr:[["alpha",1],["focalLength",200],["center_z",100],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",45],["rotationY",45],["rotationZ",45],["ran_size",256],["dimension",1],["progress",0],["follow",true],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["ran_size",256],["dimension",1],["progress",1],["follow",true]]
					},
					{
						name:"燥动出现",
						fromParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["ran_size",1],["dimension",1],["progress",0],["follow",false],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["ran_size",256],["dimension",1],["progress",1],["follow",false]]
					},
					{
						name:"风向右上角吹",
						fromParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["ran_size",256],["dimension",1],["progress",0],["follow",false],["useFrames",true]],
						toParamArr:[["center",new Float2(142,-8)],["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["ran_size",256],["dimension",1],["progress",1],["follow",false]]
					},
					{
						name:"风向右上角吹2",
						fromParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",45],["rotationX",0],["rotationY",0],["rotationZ",0],["ran_size",256],["dimension",1],["progress",0],["follow",false],["useFrames",true]],
						toParamArr:[["center",new Float2(211,-26)],["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["ran_size",256],["dimension",1],["progress",1],["follow",false]]
					}
				]
			},
			{
				as3ShaderClass:zero.shaders.as3s.classic.AS3Penjian,
				shaderClass:zero.shaders.classic.Penjian,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[]
			},
			{
				as3ShaderClass:zero.shaders.as3s.classic.AS3Pingpu,
				shaderClass:zero.shaders.classic.Pingpu,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[
					{
						name:"从远到近",
						fromParamArr:[["alpha",1],["focalLength",200],["center_z",1024],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",45],["rotationY",45],["rotationZ",45],["dis",20],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["dis",20]]
					}
				]
			},
			{
				as3ShaderClass:zero.shaders.as3s.classic.AS3Pixelate,
				shaderClass:zero.shaders.classic.Pixelate,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[
					{
						name:"溶解",
						fromParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",1],["dimension",1],["dis",0],["useFrames",true]],
						toParamArr:[["alpha",0],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",1],["dimension",10],["dis",0]]
					},
					{
						name:"旋转颗粒",
						fromParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",-90],["style",0],["dimension",10],["dis",0],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",0],["dimension",10],["dis",0]]
					}
				]
			},
			{
				as3ShaderClass:zero.shaders.as3s.classic.AS3Waiqu,
				shaderClass:zero.shaders.classic.Waiqu,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[
					{
						name:"旗帜",
						fromParamArr:[["center",new Float2(0,60)],["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["strength",10],["w",0.1],["value1",0],["value2",1],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["strength",10],["w",0.1],["value1",0],["value2",1]]
					},
					{
						name:"合上",
						fromParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["strength",0],["w",0.1],["value1",0],["value2",1],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["strength",0],["w",0],["value1",-1],["value2",1]]
					}
				]
			},
			{
				as3ShaderClass:zero.shaders.as3s.classic.AS3Wanhuatong,
				shaderClass:zero.shaders.classic.Wanhuatong,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[
					{
						name:"突然出现",
						fromParamArr:[["alpha",1],["num",16],["scale",4],["angle",-360],["useFrames",true]],
						toParamArr:[["alpha",1],["num",1],["scale",1],["angle",0]]
					}
				]
			},
			{
				as3ShaderClass:zero.shaders.as3s.classic.AS3Xingzhuangzhezhao1,
				shaderClass:zero.shaders.classic.Xingzhuangzhezhao1,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[
					{
						name:"透明椭圆出现",
						fromParamArr:[["center",new Float2(64,59)],["alpha",0],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",0],["isMask",true],["width",120],["height",100],["follow",false],["useFrames",true]],
						toParamArr:[["center",new Float2(64,59)],["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",0],["isMask",true],["width",120],["height",100],["follow",false]]
					},
					{
						name:"透明椭圆出现2",
						fromParamArr:[["center",new Float2(29,96)],["alpha",0],["focalLength",200],["center_z",0],["scaleX",0.1],["scaleY",0.1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",0],["isMask",true],["width",120],["height",100],["follow",true],["useFrames",true]],
						toParamArr:[["center",new Float2(95,52)],["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",0],["isMask",true],["width",120],["height",100],["follow",true]]
					},
					{
						name:"从左到右出现",
						fromParamArr:[["center",new Float2(0,0)],["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",1],["isMask",true],["width",0],["height",10000],["follow",false],["useFrames",true]],
						toParamArr:[["center",new Float2(0,0)],["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",1],["isMask",true],["width",320],["height",10000],["follow",false]]
					},
					{
						name:"左上角矩形出现",
						fromParamArr:[["center",new Float2(0,0)],["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",1],["isMask",true],["width",0],["height",0],["follow",false],["useFrames",true]],
						toParamArr:[["center",new Float2(0,0)],["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",1],["isMask",true],["width",320],["height",240],["follow",false]]
					},
					{
						name:"中间菱形出现",
						fromParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",2],["isMask",true],["width",0],["height",0],["follow",false],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",2],["isMask",true],["width",400],["height",200],["follow",false]]
					},
					{
						name:"矩形四周向中间合拢",
						fromParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",1],["isMask",false],["width",160],["height",120],["follow",false],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",1],["isMask",false],["width",0],["height",0],["follow",false]]
					},
					{
						name:"斜线中间打开",
						fromParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",45],["skewY",45],["rotationX",0],["rotationY",0],["rotationZ",0],["style",1],["isMask",true],["width",2048],["height",0],["follow",false],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",45],["skewY",45],["rotationX",0],["rotationY",0],["rotationZ",0],["style",1],["isMask",true],["width",2048],["height",200],["follow",false]]
					},
					{
						name:"心移到狗狗脸上",
						fromParamArr:[["center",new Float2(27,113)],["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",3],["isMask",true],["width",0],["height",0],["follow",false],["useFrames",true]],
						toParamArr:[["center",new Float2(91,47)],["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",3],["isMask",true],["width",50],["height",50],["follow",false]]
					},
					{
						name:"心掉到狗狗脸上",
						fromParamArr:[["center",new Float2(78,78)],["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",3],["isMask",false],["width",300],["height",300],["follow",false],["useFrames",true]],
						toParamArr:[["center",new Float2(92,49)],["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",720],["skewY",720],["rotationX",0],["rotationY",0],["rotationZ",0],["style",3],["isMask",false],["width",0],["height",0],["follow",false]]
					}
				]
			},
			{
				as3ShaderClass:zero.shaders.as3s.classic.AS3Xingzhuangzhezhao2,
				shaderClass:zero.shaders.classic.Xingzhuangzhezhao2,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[
					{
						name:"菊花旋转出现",
						fromParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",1],["isMask",true],["width",0],["height",0],["num",1],["value1",1],["value2",1],["value3",0],["follow",false],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",10],["scaleY",10],["skewX",360],["skewY",360],["rotationX",0],["rotationY",0],["rotationZ",0],["style",1],["isMask",true],["width",1],["height",1],["num",64],["value1",1],["value2",1],["value3",0],["follow",false]]
					},
					{
						name:"十字从中间打开",
						fromParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",1],["isMask",false],["width",0],["height",0],["num",4],["value1",1],["value2",1],["value3",0],["follow",false],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",1],["isMask",false],["width",120],["height",120],["num",4],["value1",1],["value2",1],["value3",0],["follow",false]]
					},
					{
						name:"五角星旋转出现",
						fromParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",0],["scaleY",0],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",2],["isMask",true],["width",200],["height",200],["num",5],["value1",1],["value2",1],["value3",0.32],["follow",false],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",360],["skewY",360],["rotationX",0],["rotationY",0],["rotationZ",0],["style",2],["isMask",true],["width",200],["height",200],["num",5],["value1",1],["value2",1],["value3",0.32],["follow",false]]
					},
					{
						name:"一圈心旋转出现",
						fromParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",3],["isMask",true],["width",100],["height",100],["num",10],["value1",0.2],["value2",0],["value3",1],["follow",false],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",360],["skewY",360],["rotationX",0],["rotationY",0],["rotationZ",0],["style",3],["isMask",true],["width",100],["height",100],["num",10],["value1",0.2],["value2",1],["value3",1],["follow",false]]
					},
					{
						name:"斜线左上角打开",
						fromParamArr:[["center",new Float2(0,0)],["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",135],["skewY",135],["rotationX",0],["rotationY",0],["rotationZ",0],["style",2],["isMask",true],["width",0],["height",2000],["num",1],["value1",1],["value2",1],["value3",1],["follow",false],["useFrames",true]],
						toParamArr:[["center",new Float2(0,0)],["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",135],["skewY",135],["rotationX",0],["rotationY",0],["rotationZ",0],["style",2],["isMask",true],["width",2000],["height",2000],["num",1],["value1",1],["value2",1],["value3",1],["follow",false]]
					}
				]
			},
			{
				as3ShaderClass:zero.shaders.as3s.classic.AS3Xingzhuangzhezhao3,
				shaderClass:zero.shaders.classic.Xingzhuangzhezhao3,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[
					{
						name:"圆阵出现",
						fromParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",0],["isMask",true],["width",0],["height",0],["disX",20],["disY",20],["follow",false],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",0],["isMask",true],["width",30],["height",30],["disX",-10],["disY",-10],["follow",false]]
					},
					{
						name:"圆阵出现2",
						fromParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",45],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",0],["isMask",true],["width",0],["height",0],["disX",5],["disY",5],["follow",false],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",0],["isMask",true],["width",30],["height",30],["disX",-10],["disY",-10],["follow",false]]
					},
					{
						name:"方阵出现",
						fromParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",1],["isMask",true],["width",0],["height",0],["disX",20],["disY",20],["follow",false],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",1],["isMask",true],["width",20],["height",20],["disX",0],["disY",0],["follow",false]]
					},
					{
						name:"百页窗",
						fromParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",1],["isMask",true],["width",0],["height",100],["disX",30],["disY",0],["follow",false],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",1],["isMask",true],["width",30],["height",100],["disX",0],["disY",0],["follow",false]]
					},
					{
						name:"网格消失",
						fromParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",1],["isMask",false],["width",0],["height",0],["disX",1],["disY",1],["follow",false],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",360],["skewY",360],["rotationX",0],["rotationY",0],["rotationZ",0],["style",1],["isMask",false],["width",40],["height",40],["disX",0],["disY",0],["follow",false]]
					},
					{
						name:"无数心从小到大",
						fromParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",3],["isMask",true],["width",0],["height",0],["disX",0],["disY",0],["follow",false],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",360],["skewY",360],["rotationX",0],["rotationY",0],["rotationZ",0],["style",3],["isMask",true],["width",340],["height",340],["disX",0],["disY",0],["follow",false]]
					},
					{
						name:"上升出现",
						fromParamArr:[["center",new Float2(81,121)],["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",2],["isMask",true],["width",0],["height",0],["disX",20],["disY",20],["follow",false],["useFrames",true]],
						toParamArr:[["alpha",1],["focalLength",200],["center_z",0],["scaleX",1],["scaleY",1],["skewX",0],["skewY",0],["rotationX",0],["rotationY",0],["rotationZ",0],["style",2],["isMask",true],["width",40],["height",40],["disX",-20],["disY",-20],["follow",false]]
					}
				]
			},
			{
				as3ShaderClass:zero.shaders.as3s.classic.AS3Yuanqiepian,
				shaderClass:zero.shaders.classic.Yuanqiepian,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[
					{
						name:"旋涡",
						fromParamArr:[["alpha",1],["num",10],["radius",0],["angle",360],["alpha1",1],["alpha2",0],["showOutside",false],["useFrames",true]],
						toParamArr:[["alpha",1],["num",10],["radius",326],["angle",0],["alpha1",1],["alpha2",1],["showOutside",false]]
					}
				]
			}
		]},
		{name:"www.iquilezles.org",shaderArr:[
			{
				as3ShaderClass:zero.shaders.as3s.shadertoy.AS3Deform,
				shaderClass:zero.shaders.shadertoy.Deform,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[
					{
						name:"右下角到左上角",
						fromParamArr:[["center",new Float2(0,0)],["alpha",1],["time",0],["useFrames",true]],
						toParamArr:[["center",new Float2(0,0)],["alpha",1],["time",10]]
					}
				]
			},
			{
				as3ShaderClass:zero.shaders.as3s.shadertoy.AS3Earth,
				shaderClass:zero.shaders.shadertoy.Earth,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[]
			},
			{
				as3ShaderClass:zero.shaders.as3s.shadertoy.AS3Flower,
				shaderClass:zero.shaders.shadertoy.Flower,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[]
			},
			{
				as3ShaderClass:zero.shaders.as3s.shadertoy.AS3Fly,
				shaderClass:zero.shaders.shadertoy.Fly,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[]
			},
			{
				as3ShaderClass:zero.shaders.as3s.shadertoy.AS3Heart,
				shaderClass:zero.shaders.shadertoy.Heart,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[]
			},
			{
				as3ShaderClass:zero.shaders.as3s.shadertoy.AS3Kaleidoscope,
				shaderClass:zero.shaders.shadertoy.Kaleidoscope,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[]
			},
			{
				as3ShaderClass:zero.shaders.as3s.shadertoy.AS3Metablob,
				shaderClass:zero.shaders.shadertoy.Metablob,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[]
			},
			{
				as3ShaderClass:zero.shaders.as3s.shadertoy.AS3Monjori,
				shaderClass:zero.shaders.shadertoy.Monjori,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[]
			},
			{
				as3ShaderClass:zero.shaders.as3s.shadertoy.AS3Plasma,
				shaderClass:zero.shaders.shadertoy.Plasma,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[]
			},
			{
				as3ShaderClass:zero.shaders.as3s.shadertoy.AS3Postprocessing,
				shaderClass:zero.shaders.shadertoy.Postprocessing,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[]
			},
			{
				as3ShaderClass:zero.shaders.as3s.shadertoy.AS3Pulse,
				shaderClass:zero.shaders.shadertoy.Pulse,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[]
			},
			{
				as3ShaderClass:zero.shaders.as3s.shadertoy.AS3RadialBlur,
				shaderClass:zero.shaders.shadertoy.RadialBlur,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[]
			},
			{
				as3ShaderClass:zero.shaders.as3s.shadertoy.AS3ReliefTunnel,
				shaderClass:zero.shaders.shadertoy.ReliefTunnel,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[]
			},
			{
				as3ShaderClass:zero.shaders.as3s.shadertoy.AS3SquareTunnel,
				shaderClass:zero.shaders.shadertoy.SquareTunnel,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[]
			},
			{
				as3ShaderClass:zero.shaders.as3s.shadertoy.AS3Star,
				shaderClass:zero.shaders.shadertoy.Star,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[]
			},
			{
				as3ShaderClass:zero.shaders.as3s.shadertoy.AS3Tunnel,
				shaderClass:zero.shaders.shadertoy.Tunnel,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[]
			},
			{
				as3ShaderClass:zero.shaders.as3s.shadertoy.AS3Twist,
				shaderClass:zero.shaders.shadertoy.Twist,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[]
			},
			{
				as3ShaderClass:zero.shaders.as3s.shadertoy.AS3ZInvert,
				shaderClass:zero.shaders.shadertoy.ZInvert,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[]
			}
		]},
		{name:"测试",shaderArr:[
			{
				as3ShaderClass:zero.shaders.as3s.test.AS3ARGB,
				shaderClass:zero.shaders.test.ARGB,
				as3EffectClass:zero.stage3Ds.as3s.test.AS3ARGB,
				effectClass:zero.stage3Ds.test.ARGB,
				defaultParamsArr:[
					{
						name:"变红",
						fromParamArr:[["alpha",1],["red",1],["green",1],["blue",1],["useFrames",true]],
						toParamArr:[["alpha",1],["red",1],["green",0],["blue",0]]
					}
				]
			},
			{
				as3ShaderClass:zero.shaders.as3s.test.AS3Chessboard,
				shaderClass:zero.shaders.test.Chessboard,
				as3EffectClass:zero.stage3Ds.as3s.test.AS3Chessboard,
				effectClass:zero.stage3Ds.test.Chessboard,
				defaultParamsArr:[
					{
						name:"黑白",
						fromParamArr:[["alpha",1],["dimension",10],["color1",new Pixel4(1,1,1,1)],["color2",new Pixel4(0,0,0,1)],["useFrames",true]],
						toParamArr:[["alpha",1],["dimension",10],["color1",new Pixel4(1,1,1,1)],["color2",new Pixel4(0,0,0,1)]]
					}
				]
			},
			{
				as3ShaderClass:zero.shaders.as3s.test.AS3RippleFilter,
				shaderClass:zero.shaders.test.RippleFilter,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[
					{
						name:"水波纹",
						fromParamArr:[["alpha",1],["displacement",6],["size",550],["ripplewidth",20],["phase",-10],["lightbright",0.003],["useFrames",true]],
						toParamArr:[["alpha",1],["displacement",6],["size",550],["ripplewidth",20],["phase",10],["lightbright",0.003]]
					}
				]
			},
			{
				as3ShaderClass:zero.shaders.as3s.test.AS3SampleTest,
				shaderClass:zero.shaders.test.SampleTest,
				as3EffectClass:zero.stage3Ds.as3s.test.AS3SampleTest,
				effectClass:zero.stage3Ds.test.SampleTest,
				defaultParamsArr:[]
			},
			{
				as3ShaderClass:zero.shaders.as3s.test.AS3Shunxi,
				shaderClass:zero.shaders.test.Shunxi,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[
					{
						name:"从左上角吸入",
						fromParamArr:[["center",new Float2(0,0)],["alpha",1],["progress",0],["useFrames",true]],
						toParamArr:[["center",new Float2(0,0)],["alpha",1],["progress",1]]
					}
				]
			},
			{
				as3ShaderClass:zero.shaders.as3s.test.AS3Smudger,
				shaderClass:zero.shaders.test.Smudger,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[
					{
						name:"出现",
						fromParamArr:[["alpha",1],["dimension",5],["amount",5],["useFrames",true]],
						toParamArr:[["alpha",1],["dimension",5],["amount",0]]
					}
				]
			},
			{
				as3ShaderClass:zero.shaders.as3s.test.AS3Test,
				shaderClass:zero.shaders.test.Test,
				as3EffectClass:zero.stage3Ds.as3s.test.AS3Test,
				effectClass:zero.stage3Ds.test.Test,
				defaultParamsArr:[
					{
						name:"测试uvxiuzheng",
						fromParamArr:[["center",new Float2(125,21)],["alpha",1],["dimension",10],["useFrames",true]],
						toParamArr:[["center",new Float2(105,78)],["alpha",1],["dimension",68]]
					}
				]
			},
			{
				as3ShaderClass:zero.shaders.as3s.test.AS3Wave,
				shaderClass:zero.shaders.test.Wave,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[
					{
						name:"干涉图样",
						fromParamArr:[["center1",new Float2(30,30)],["center2",new Float2(130,30)],["alpha",1],["A1",4],["w1",1],["q1",0],["A2",4],["w2",1],["q2",0],["useFrames",true]],
						toParamArr:[["center1",new Float2(30,30)],["center2",new Float2(130,30)],["alpha",1],["A1",4],["w1",1],["q1",4],["A2",4],["w2",1],["q2",4]]
					},
					{
						name:"出现",
						fromParamArr:[["alpha",0],["A1",10],["w1",0.3],["q1",0],["A2",10],["w2",0.3],["q2",0],["useFrames",true]],
						toParamArr:[["alpha",1],["A1",0],["w1",0],["q1",5],["A2",0],["w2",0],["q2",5]]
					},
					{
						name:"出现2",
						fromParamArr:[["center1",new Float2(40,60)],["center2",new Float2(120,60)],["alpha",0],["A1",10],["w1",0.3],["q1",0],["A2",10],["w2",0.3],["q2",0],["useFrames",true]],
						toParamArr:[["center1",new Float2(40,60)],["center2",new Float2(120,60)],["alpha",1],["A1",0],["w1",0],["q1",5],["A2",0],["w2",0],["q2",5]]
					}
				]
			},
			{
				as3ShaderClass:zero.shaders.as3s.test.AS3WaveReflection,
				shaderClass:zero.shaders.test.WaveReflection,
				as3EffectClass:null,
				effectClass:null,
				defaultParamsArr:[]
			}
		]}
	];
}
