/***
Op 版本:v1.0
简要说明:这家伙很懒什么都没写
创建人:ZЁЯ¤  身高:168cm+;体重:57kg+;未婚(已有女友);最爱的运动:睡觉;格言:路见不平,拔腿就跑;QQ:358315553
创建时间:2010年11月8日 15:11:36 (代码生成器: F:/airs/program files2/CodesGenerater/bin-debug/CodesGenerater.swf) 
历次修改:未有修改
用法举例:这家伙很懒什么都没写
*/

package zero.swf.avm1{

	public class Op{
		public static const end:int=0;
		public static const nextFrame:int=4;
		public static const prevFrame:int=5;
		public static const play:int=6;
		public static const stop:int=7;
		public static const toggleQuality:int=8;
		public static const stopSounds:int=9;
		public static const oldAdd:int=10;
		public static const subtract:int=11;
		public static const multiply:int=12;
		public static const divide:int=13;
		public static const oldEquals:int=14;
		public static const oldLessThan:int=15;
		public static const and:int=16;
		public static const or:int=17;
		public static const not:int=18;
		public static const stringEq:int=19;
		public static const stringLength:int=20;
		public static const substring:int=21;
		public static const pop:int=23;
		public static const int_:int=24;
		public static const getVariable:int=28;
		public static const setVariable:int=29;
		public static const setTargetExpr:int=32;
		public static const concat:int=33;
		public static const getProperty:int=34;
		public static const setProperty:int=35;
		public static const duplicateClip:int=36;
		public static const removeClip:int=37;
		public static const trace_:int=38;
		public static const startDrag:int=39;
		public static const stopDrag:int=40;
		public static const stringLess:int=41;
		public static const throw_:int=42;
		public static const cast:int=43;
		public static const implements_:int=44;
		public static const FSCommand2:int=45;
		public static const random:int=48;
		public static const mBStringLength:int=49;
		public static const ord:int=50;
		public static const chr:int=51;
		public static const getTimer:int=52;
		public static const mbSubstring:int=53;
		public static const mbOrd:int=54;
		public static const mbChr:int=55;
		public static const delete_:int=58;
		public static const delete2:int=59;
		public static const varEquals:int=60;
		public static const callFunction:int=61;
		public static const return_:int=62;
		public static const modulo:int=63;
		public static const new_:int=64;
		public static const var_:int=65;
		public static const initArray:int=66;
		public static const initObject:int=67;
		public static const typeof_:int=68;
		public static const targetPath:int=69;
		public static const enumerate:int=70;
		public static const add:int=71;
		public static const lessThan:int=72;
		public static const equals:int=73;
		public static const toNumber:int=74;
		public static const toString_:int=75;
		public static const dup:int=76;
		public static const swap:int=77;
		public static const getMember:int=78;
		public static const setMember:int=79;
		public static const increment:int=80;
		public static const decrement:int=81;
		public static const callMethod:int=82;
		public static const newMethod:int=83;
		public static const instanceOf:int=84;
		public static const enumerateValue:int=85;
		public static const bitwiseAnd:int=96;
		public static const bitwiseOr:int=97;
		public static const bitwiseXor:int=98;
		public static const shiftLeft:int=99;
		public static const shiftRight:int=100;
		public static const shiftRight2:int=101;
		public static const strictEquals:int=102;
		public static const greaterThan:int=103;
		public static const stringGreater:int=104;
		public static const extends_:int=105;
		public static const gotoFrame:int=129;
		public static const getURL:int=131;
		public static const setRegister:int=135;
		public static const constants:int=136;
		public static const ifFrameLoaded:int=138;
		public static const setTarget:int=139;
		public static const gotoLabel:int=140;
		public static const ifFrameLoadedExpr:int=141;
		public static const function2:int=142;
		public static const try_:int=143;
		public static const with_:int=148;
		public static const push:int=150;
		public static const branch:int=153;
		public static const getURL2:int=154;
		public static const function_:int=155;
		public static const branchIfTrue:int=157;
		public static const callFrame:int=158;
		public static const gotoFrame2:int=159;
		
		public static const opNameV:Vector.<String>=get_opNameV();
		private static function get_opNameV():Vector.<String>{
			var opNameV:Vector.<String>=new Vector.<String>(256);
			opNameV.fixed=true;
			opNameV[0]="end";
			opNameV[4]="nextFrame";
			opNameV[5]="prevFrame";
			opNameV[6]="play";
			opNameV[7]="stop";
			opNameV[8]="toggleQuality";
			opNameV[9]="stopSounds";
			opNameV[10]="oldAdd";
			opNameV[11]="subtract";
			opNameV[12]="multiply";
			opNameV[13]="divide";
			opNameV[14]="oldEquals";
			opNameV[15]="oldLessThan";
			opNameV[16]="and";
			opNameV[17]="or";
			opNameV[18]="not";
			opNameV[19]="stringEq";
			opNameV[20]="stringLength";
			opNameV[21]="substring";
			opNameV[23]="pop";
			opNameV[24]="int_";
			opNameV[28]="getVariable";
			opNameV[29]="setVariable";
			opNameV[32]="setTargetExpr";
			opNameV[33]="concat";
			opNameV[34]="getProperty";
			opNameV[35]="setProperty";
			opNameV[36]="duplicateClip";
			opNameV[37]="removeClip";
			opNameV[38]="trace_";
			opNameV[39]="startDrag";
			opNameV[40]="stopDrag";
			opNameV[41]="stringLess";
			opNameV[42]="throw_";
			opNameV[43]="cast";
			opNameV[44]="implements_";
			opNameV[45]="FSCommand2";
			opNameV[48]="random";
			opNameV[49]="mBStringLength";
			opNameV[50]="ord";
			opNameV[51]="chr";
			opNameV[52]="getTimer";
			opNameV[53]="mbSubstring";
			opNameV[54]="mbOrd";
			opNameV[55]="mbChr";
			opNameV[58]="delete_";
			opNameV[59]="delete2";
			opNameV[60]="varEquals";
			opNameV[61]="callFunction";
			opNameV[62]="return_";
			opNameV[63]="modulo";
			opNameV[64]="new_";
			opNameV[65]="var_";
			opNameV[66]="initArray";
			opNameV[67]="initObject";
			opNameV[68]="typeof_";
			opNameV[69]="targetPath";
			opNameV[70]="enumerate";
			opNameV[71]="add";
			opNameV[72]="lessThan";
			opNameV[73]="equals";
			opNameV[74]="toNumber";
			opNameV[75]="toString_";
			opNameV[76]="dup";
			opNameV[77]="swap";
			opNameV[78]="getMember";
			opNameV[79]="setMember";
			opNameV[80]="increment";
			opNameV[81]="decrement";
			opNameV[82]="callMethod";
			opNameV[83]="newMethod";
			opNameV[84]="instanceOf";
			opNameV[85]="enumerateValue";
			opNameV[96]="bitwiseAnd";
			opNameV[97]="bitwiseOr";
			opNameV[98]="bitwiseXor";
			opNameV[99]="shiftLeft";
			opNameV[100]="shiftRight";
			opNameV[101]="shiftRight2";
			opNameV[102]="strictEquals";
			opNameV[103]="greaterThan";
			opNameV[104]="stringGreater";
			opNameV[105]="extends_";
			opNameV[129]="gotoFrame";
			opNameV[131]="getURL";
			opNameV[135]="setRegister";
			opNameV[136]="constants";
			opNameV[138]="ifFrameLoaded";
			opNameV[139]="setTarget";
			opNameV[140]="gotoLabel";
			opNameV[141]="ifFrameLoadedExpr";
			opNameV[142]="function2";
			opNameV[143]="try_";
			opNameV[148]="with_";
			opNameV[150]="push";
			opNameV[153]="branch";
			opNameV[154]="getURL2";
			opNameV[155]="function_";
			opNameV[157]="branchIfTrue";
			opNameV[158]="callFrame";
			opNameV[159]="gotoFrame2";
			return opNameV;
		}
		
		////
		//

	}
}